### ISSUE TITLE
Better way to know when logged out

### ISSUE THREAD

**Issue by phorcys420** [mautrix/instagram#116]
I've experienced a number of disconnects since my first use of the bridge (october 2021), and each time, I fail to know that I've been disconnected.

I have the bot's DMs muted because honestly, who likes this stuff ?
![image](https://user-images.githubusercontent.com/57866459/235175321-2c7f2ffb-7ad8-45f4-bab3-71f00a66f197.png)

That's not really an issue, but when I get the log out messages, I don't know about them and usually spend around 30 minutes to 3 hours to notice that my friends haven't been ghosting me ! (I have a specific space for friends and a specific space for bridges)

I think it could be improved.
Now, I have some ideas in mind :
- Puppeted rooms could send you a message when you're logged out. Issue with that is that it will move the message reads in an improper manner.
- The bridge bot should ping the user it's in DMs with when something is important, that way I set the bot's DMs to pings/keywords only.

**Comment by tulir** [comment]
You can disable the unimportant notices https://github.com/mautrix/instagram/blob/master/mautrix_instagram/example-config.yaml#L302-L304

**Comment by phorcys420** [comment]
oh, thanks for the heads up !
I guess I'll close this then.
