### ISSUE TITLE
How to restore saved state?

### ISSUE THREAD

**Issue by rvaidun** [mautrix/instagram#130]
Hi,
I recently ran this script
https://github.com/mautrix/instagram/blob/master/mauigpapi/scripts/iglogin.py and was able to get the state in JSON.

How do I use this state on subsequent requests so I don't have to re login?

**Comment by tulir** [comment]
Using the `login` command in the bridge does the same thing, you don't need to save anything manually

**Comment by tulir** [comment]
Using it for anything else is not supported. It's technically possible, but you'll have to figure out how it works yourself by reading the code
