### ISSUE TITLE
Shared Reels aren't sent

### ISSUE THREAD

**Issue by mibzman** [mautrix/instagram#15]
Reproduction steps:
1. View a reel on instagram
2. tap the paper airplane
3. send to yourself

for me, no message is sent from Instagram bridge bot.  If possible, I'd like to get a message that a reel failed to send so I at least know to check instagram.

**Comment by mibzman** [comment]
@tulir I'm still seeing this, but currently I just get a message that says "unsupported message type" when I get a reel.

**Comment by tulir** [comment]
That means you're using an old version of the bridge
