### ISSUE TITLE
"Typing..." Delayed ?

### ISSUE THREAD

**Issue by Mozoloa** [mautrix/instagram#43]
Hello, 

I'm using your bridge and everything works pretty well except I realized that there is a latency between the moment someone starts to write to me and the moment I see it.

So when I'm talking with someone, I see a brief "typing..." with a message straight after, then the "typing..." sticks there (or reappears) for a while and disappears randomly without any other message received. It's happening on every conversation so it's not just someone being very hesitant about their messages hehe.

Am I the only one ?

Thanks you guys

**Comment by tulir** [comment]
Should be fixed now

**Comment by Mozoloa** [comment]
This glitch is back unfortunately
