### ISSUE TITLE
Sending or receiving story in DM no longer downloads the video

### ISSUE THREAD

**Issue by ronyclau** [mautrix/instagram#78]
Sending or receiving a story in DM in Instagram app would trigger the download of the story by the bridge, as it needs to show the message in the bridged room.

However, since a month ago (roughly late November 2022), only an image would be downloaded and shown in the bridged room, regardless of the type of story. In other words, it would always download a still picture no matter the story is, indeed, a still picture, or a video.

**Comment by Mozoloa** [comment]
I just realised that as well !
