### ISSUE TITLE
Disable periodic `Connected to Instagram` message to bridge users

### ISSUE THREAD

**Issue by HammyHavoc** [mautrix/instagram#94]
How do I disable this? It's more intuitive to be told that I'm _not_ connected for any reason than to be told regularly with a notification that I _am_ connected. I recall figuring out disabling this for the Facebook Messenger bridge, how would I go about doing it for Instagram?

**Comment by HammyHavoc** [comment]
Hmm, is it the `unimportant_bridge_notices` var?

**Comment by xocite** [comment]
Looks like it.  Set it to `false`.

**Comment by HammyHavoc** [comment]
Seems like that sorted it!
